### PR TITLE
Switch to official hcor

### PR DESCRIPTION
**Pull request by cjdenio**

### CODE REVIEW

**Review by Muirrum — APPROVED** [review]

**Comment by cjdenio** [comment]
CI's still failing because https://github.com/SergioBenitez/Pear/commit/d137aa1df314e2e199470e1f54b931bf859ade89 hasn't been released yet :(

**Comment by Muirrum** [comment]
Can you pin to that commit?

**Comment by cjdenio** [comment]
I don't think so, because pear is a dependency of a dependency

**Comment by Muirrum** [comment]
I'm hesitant to merge this until the upstream issues with Pear are resolved - I don't want to break master.

**Comment by cjdenio** [comment]
Master's already broken; the only reason it still works is that the old version of pear is cached on the server

**Comment by cjdenio** [comment]
@Muirrum the CI issues seem to have been fixed! 🎉

**Review by Muirrum — APPROVED** [review]

**Pull request merged**
